// Justin M. Rowe
// Project 4
// Mobile Interface and Usability 1208 (MIU)
// Mobile Development
// Full Sail University

var json = {
	"contact1": {
		"pname": ["Project Name:", "TBI Tracker"],
		"pmfname": ["First Name:", "Justin"],
		"pmlname": ["Last Name:", "Rowe"],
		"sdate": ["Project Start Date:", "2012-01-01"],
		"fdate": ["Project Finish Date:", "2012-10-01"],
		"contractstart": ["Contract Start Date:", "2012-02-01"],
		"contractaward": ["Contract Award Date:", "2012-03-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-03-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-07-01"],
		"teststart": ["Testing Start Date:", "2012-07-15"],
		"testfinish": ["Testing Finish Date:", "2012-09-15"],
		"delivery": ["Delivery Date:", "2012-09-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "This is the first project for this year."]	
	},
	"contact2": {
		"pname": ["Project Name:", "Sport Project"],
		"pmfname": ["First Name:", "Steve"],
		"pmlname": ["Last Name:", "Hill"],
		"sdate": ["Project Start Date:", "2012-02-01"],
		"fdate": ["Project Finish Date:", "2012-11-01"],
		"contractstart": ["Contract Start Date:", "2012-03-01"],
		"contractaward": ["Contract Award Date:", "2012-04-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-04-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-08-01"],
		"teststart": ["Testing Start Date:", "2012-08-15"],
		"testfinish": ["Testing Finish Date:", "2012-10-15"],
		"delivery": ["Delivery Date:", "2012-10-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "This is the second project for this year."]		
	},
	"contact3": {
		"pname": ["Project Name:", "Robot Project"],
		"pmfname": ["First Name:", "Wesley"],
		"pmlname": ["Last Name:", "Brin"],
		"sdate": ["Project Start Date:", "2012-03-01"],
		"fdate": ["Project Finish Date:", "2012-12-01"],
		"contractstart": ["Contract Start Date:", "2012-04-01"],
		"contractaward": ["Contract Award Date:", "2012-05-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-05-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-09-01"],
		"teststart": ["Testing Start Date:", "2012-09-15"],
		"testfinish": ["Testing Finish Date:", "2012-11-15"],
		"delivery": ["Delivery Date:", "2012-11-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "This is the final project for this year."]		
	},
	"contact4": {
		"pname": ["Project Name:", "Recon Ballon"],
		"pmfname": ["First Name:", "Peter"],
		"pmlname": ["Last Name:", "Moore"],
		"sdate": ["Project Start Date:", "2012-05-15"],
		"fdate": ["Project Finish Date:", "2013-01-15"],
		"contractstart": ["Contract Start Date:", "2012-07-01"],
		"contractaward": ["Contract Award Date:", "2012-07-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-07-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-09-01"],
		"teststart": ["Testing Start Date:", "2012-11-15"],
		"testfinish": ["Testing Finish Date:", "2012-12-15"],
		"delivery": ["Delivery Date:", "2012-12-30"],
		"nocontracting": ["Contracting N/A:", "Yes"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Modified Commercial Off The Shelf"],
		"notes": ["Notes:", "This project will cost $2.5 million."]	
	},
	"contact5": {
		"pname": ["Project Name:", "Mine Detector"],
		"pmfname": ["First Name:", "Rob"],
		"pmlname": ["Last Name:", "Thomas"],
		"sdate": ["Project Start Date:", "2011-07-01"],
		"fdate": ["Project Finish Date:", "2012-03-01"],
		"contractstart": ["Contract Start Date:", "2011-08-01"],
		"contractaward": ["Contract Award Date:", "2011-09-15"],
		"productionstart": ["Vendor Production Start Date:", "2011-09-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2011-11-01"],
		"teststart": ["Testing Start Date:", "2011-11-15"],
		"testfinish": ["Testing Finish Date:", "2012-01-15"],
		"delivery": ["Delivery Date:", "2012-02-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "Yes"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "This project will use a contract through DLA."]		
	},
	"contact6": {
		"pname": ["Project Name:", "Solar Energy in a Box"],
		"pmfname": ["First Name:", "Jed"],
		"pmlname": ["Last Name:", "Simpson"],
		"sdate": ["Project Start Date:", "2012-01-15"],
		"fdate": ["Project Finish Date:", "2012-10-01"],
		"contractstart": ["Contract Start Date:", "2012-02-01"],
		"contractaward": ["Contract Award Date:", "2012-03-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-03-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-05-01"],
		"teststart": ["Testing Start Date:", "2012-06-15"],
		"testfinish": ["Testing Finish Date:", "2012-08-15"],
		"delivery": ["Delivery Date:", "2012-09-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "This is the final project for this year."]		
	},
	"contact7": {
		"pname": ["Project Name:", "Radar in a Box"],
		"pmfname": ["First Name:", "Consuela"],
		"pmlname": ["Last Name:", "Beverly"],
		"sdate": ["Project Start Date:", "2012-04-01"],
		"fdate": ["Project Finish Date:", "2012-12-01"],
		"contractstart": ["Contract Start Date:", "2012-05-01"],
		"contractaward": ["Contract Award Date:", "2012-06-01"],
		"productionstart": ["Vendor Production Start Date:", "2012-06-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-08-15"],
		"teststart": ["Testing Start Date:", "2012-09-15"],
		"testfinish": ["Testing Finish Date:", "2012-10-28"],
		"delivery": ["Delivery Date:", "2012-11-30"],
		"nocontracting": ["Contracting N/A:", "Yes"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "Contract will be funded incrementally."]	
	},
	"contact8": {
		"pname": ["Project Name:", "ISR Software Package"],
		"pmfname": ["First Name:", "Gary"],
		"pmlname": ["Last Name:", "West"],
		"sdate": ["Project Start Date:", "2012-01-15"],
		"fdate": ["Project Finish Date:", "2013-01-15"],
		"contractstart": ["Contract Start Date:", "2012-04-01"],
		"contractaward": ["Contract Award Date:", "2012-06-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-06-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-10-01"],
		"teststart": ["Testing Start Date:", "2012-10-15"],
		"testfinish": ["Testing Finish Date:", "2012-12-15"],
		"delivery": ["Delivery Date:", "2012-12-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "This is the fifth project for this year."]		
	},
	"contact9": {
		"pname": ["Project Name:", "Mobile Communications Equipment"],
		"pmfname": ["First Name:", "Eric"],
		"pmlname": ["Last Name:", "McCray"],
		"sdate": ["Project Start Date:", "2012-08-01"],
		"fdate": ["Project Finish Date:", "2012-04-01"],
		"contractstart": ["Contract Start Date:", "2012-09-01"],
		"contractaward": ["Contract Award Date:", "2012-10-02"],
		"productionstart": ["Vendor Production Start Date:", "2012-10-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-12-01"],
		"teststart": ["Testing Start Date:", "2012-01-15"],
		"testfinish": ["Testing Finish Date:", "2012-02-15"],
		"delivery": ["Delivery Date:", "2012-03-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "Two vendors are combining efforts to produce a prototype."]		
	},
	"contact10": {
		"pname": ["Project Name:", "Mobile Funding Application"],
		"pmfname": ["First Name:", "Shannon"],
		"pmlname": ["Last Name:", "Wilson"],
		"sdate": ["Project Start Date:", "2012-06-01"],
		"fdate": ["Project Finish Date:", "2012-11-01"],
		"contractstart": ["Contract Start Date:", "2012-06-16"],
		"contractaward": ["Contract Award Date:", "2012-07-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-07-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-09-15"],
		"teststart": ["Testing Start Date:", "2012-10-01"],
		"testfinish": ["Testing Finish Date:", "2012-10-15"],
		"delivery": ["Delivery Date:", "2012-10-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "Yes"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Modified Commercial Off The Shelf"],
		"notes": ["Notes:", "Application will need to work on Apple iPad."]	
	},
	"contact11": {
		"pname": ["Project Name:", "Radar Detection Unit"],
		"pmfname": ["First Name:", "Brian"],
		"pmlname": ["Last Name:", "Fila"],
		"sdate": ["Project Start Date:", "2011-08-01"],
		"fdate": ["Project Finish Date:", "2012-05-01"],
		"contractstart": ["Contract Start Date:", "2011-09-01"],
		"contractaward": ["Contract Award Date:", "2011-10-15"],
		"productionstart": ["Vendor Production Start Date:", "2011-11-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-02-01"],
		"teststart": ["Testing Start Date:", "2012-03-15"],
		"testfinish": ["Testing Finish Date:", "2012-04-15"],
		"delivery": ["Delivery Date:", "2012-04-30"],
		"nocontracting": ["Contracting N/A:", "Yes"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "Yes"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "No notes for this project."]		
	},
	"contact12": {
		"pname": ["Project Name:", "Light Tactical ATV"],
		"pmfname": ["First Name:", "Wesley"],
		"pmlname": ["Last Name:", "Brin"],
		"sdate": ["Project Start Date:", "2012-04-12"],
		"fdate": ["Project Finish Date:", "2012-12-01"],
		"contractstart": ["Contract Start Date:", "2012-05-01"],
		"contractaward": ["Contract Award Date:", "2012-06-28"],
		"productionstart": ["Vendor Production Start Date:", "2012-07-27"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-09-01"],
		"teststart": ["Testing Start Date:", "2012-09-15"],
		"testfinish": ["Testing Finish Date:", "2012-10-12"],
		"delivery": ["Delivery Date:", "2012-11-04"],
		"nocontracting": ["Contracting N/A:", "Yes"],
		"notesting": ["Testing N/A:", "Yes"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Modified Commercial Off The Shelf"],
		"notes": ["Notes:", "ATV's will come from three vendors for testing."]		
	},
	"contact13": {
		"pname": ["Project Name:", "Blast Sensor Suite"],
		"pmfname": ["First Name:", "Joe"],
		"pmlname": ["Last Name:", "Smith"],
		"sdate": ["Project Start Date:", "2012-04-10"],
		"fdate": ["Project Finish Date:", "2013-01-05"],
		"contractstart": ["Contract Start Date:", "2012-06-01"],
		"contractaward": ["Contract Award Date:", "2012-07-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-07-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-09-10"],
		"teststart": ["Testing Start Date:", "2012-10-15"],
		"testfinish": ["Testing Finish Date:", "2012-11-15"],
		"delivery": ["Delivery Date:", "2012-12-30"],
		"nocontracting": ["Contracting N/A:", "Yes"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "Yes"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "This will be the first order of three."]	
	},
	"contact14": {
		"pname": ["Project Name:", "Portable Water Systems"],
		"pmfname": ["First Name:", "Joy"],
		"pmlname": ["Last Name:", "Bonham"],
		"sdate": ["Project Start Date:", "2012-07-01"],
		"fdate": ["Project Finish Date:", "2013-01-01"],
		"contractstart": ["Contract Start Date:", "2012-08-01"],
		"contractaward": ["Contract Award Date:", "2012-08-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-09-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-11-04"],
		"teststart": ["Testing Start Date:", "2012-11-15"],
		"testfinish": ["Testing Finish Date:", "2012-12-15"],
		"delivery": ["Delivery Date:", "2012-12-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "The vendor will send in two prototypes for testing."]		
	},
	"contact15": {
		"pname": ["Project Name:", "EOD Interrogation Knife"],
		"pmfname": ["First Name:", "Rob"],
		"pmlname": ["Last Name:", "Thomas"],
		"sdate": ["Project Start Date:", "2012-02-01"],
		"fdate": ["Project Finish Date:", "2012-10-01"],
		"contractstart": ["Contract Start Date:", "2012-04-20"],
		"contractaward": ["Contract Award Date:", "2012-06-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-06-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-08-03"],
		"teststart": ["Testing Start Date:", "2012-08-17"],
		"testfinish": ["Testing Finish Date:", "2012-09-15"],
		"delivery": ["Delivery Date:", "2012-09-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "Yes"],
		"notraining": ["Training N/A:", "Yes"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "Order will need to be placed for 500 knives."]		
	},
	"contact16": {
		"pname": ["Project Name:", "Mortar Prevention Systems"],
		"pmfname": ["First Name:", "Justin"],
		"pmlname": ["Last Name:", "Rowe"],
		"sdate": ["Project Start Date:", "2012-02-15"],
		"fdate": ["Project Finish Date:", "2012-10-01"],
		"contractstart": ["Contract Start Date:", "2012-04-01"],
		"contractaward": ["Contract Award Date:", "2012-05-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-05-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-07-01"],
		"teststart": ["Testing Start Date:", "2012-07-15"],
		"testfinish": ["Testing Finish Date:", "2012-09-15"],
		"delivery": ["Delivery Date:", "2012-09-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "Systems will take 45 days to produce."]	
	},
	"contact17": {
		"pname": ["Project Name:", "Radar Jamming Systems"],
		"pmfname": ["First Name:", "Tim"],
		"pmlname": ["Last Name:", "Harrison"],
		"sdate": ["Project Start Date:", "2012-02-01"],
		"fdate": ["Project Finish Date:", "2012-11-01"],
		"contractstart": ["Contract Start Date:", "2012-03-01"],
		"contractaward": ["Contract Award Date:", "2012-04-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-05-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-08-01"],
		"teststart": ["Testing Start Date:", "2012-09-15"],
		"testfinish": ["Testing Finish Date:", "2012-10-15"],
		"delivery": ["Delivery Date:", "2012-10-30"],
		"nocontracting": ["Contracting N/A:", "Yes"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "Will need to be equipped with remote aircraft."]		
	},
	"contact18": {
		"pname": ["Project Name:", "Robot Project 2"],
		"pmfname": ["First Name:", "Wesley"],
		"pmlname": ["Last Name:", "Brin"],
		"sdate": ["Project Start Date:", "2012-05-01"],
		"fdate": ["Project Finish Date:", "2013-01-04"],
		"contractstart": ["Contract Start Date:", "2012-06-01"],
		"contractaward": ["Contract Award Date:", "2012-07-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-08-28"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-10-01"],
		"teststart": ["Testing Start Date:", "2012-11-15"],
		"testfinish": ["Testing Finish Date:", "2012-12-15"],
		"delivery": ["Delivery Date:", "2012-12-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "No"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "This will be the next development of the previous project."]		
	},
		"contact19": {
		"pname": ["Project Name:", "Tactical Land Mobile Radios"],
		"pmfname": ["First Name:", "Steve"],
		"pmlname": ["Last Name:", "Hill"],
		"sdate": ["Project Start Date:", "2012-04-01"],
		"fdate": ["Project Finish Date:", "2012-12-10"],
		"contractstart": ["Contract Start Date:", "2012-05-01"],
		"contractaward": ["Contract Award Date:", "2012-07-15"],
		"productionstart": ["Vendor Production Start Date:", "2012-07-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2012-09-06"],
		"teststart": ["Testing Start Date:", "2012-09-15"],
		"testfinish": ["Testing Finish Date:", "2012-10-15"],
		"delivery": ["Delivery Date:", "2012-11-30"],
		"nocontracting": ["Contracting N/A:", "No"],
		"notesting": ["Testing N/A:", "Yes"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Commercial Off The Shelf"],
		"notes": ["Notes:", "Radios will require additional spare parts."]		
	},
	"contact20": {
		"pname": ["Project Name:", "Tactical Motorcycles"],
		"pmfname": ["First Name:", "Wesley"],
		"pmlname": ["Last Name:", "Brin"],
		"sdate": ["Project Start Date:", "2011-08-01"],
		"fdate": ["Project Finish Date:", "2012-04-01"],
		"contractstart": ["Contract Start Date:", "2011-09-07"],
		"contractaward": ["Contract Award Date:", "2011-09-28"],
		"productionstart": ["Vendor Production Start Date:", "2011-10-16"],
		"productionfinish": ["Vendor Production Finish Date:", "2011-12-01"],
		"teststart": ["Testing Start Date:", "2012-01-15"],
		"testfinish": ["Testing Finish Date:", "2012-03-15"],
		"delivery": ["Delivery Date:", "2012-03-30"],
		"nocontracting": ["Contracting N/A:", "Yes"],
		"notesting": ["Testing N/A:", "Yes"],
		"notraining": ["Training N/A:", "No"],
		"group": ["Product Type:", "Research and Development"],
		"notes": ["Notes:", "Contracting support will last for two years."]		
	}  
}